character_name = "jim"
character_age = "58"
print("jim went to the store to get some rope, " + character_name +", tied it to a sturdy branch ")
print("the man named " + character_name + " is "  + character_age +", ")
print("jim spent most of his mornings in bed. " + character_name + " was fed up with it, fed up with life ")
print("as jim went back to the tree he left the day before " + character_name +" tied a special knot, it wasnt a special moment, he felt nothing, like every day for the past 58 years ")
print(" jim was about to step up to the rope when he realized something " + character_name + " forgot his wooden stool at his house ")
print(" as jim drove home he thought about all of his deceased family and friends " + character_name + " was the only one left now, there was no point ")
print(" as he opened his small bedside cabnit " + character_name + " spotted something else, something much more intresting. ")
print(" he gets in the car at 12:43 " + character_name + " did not think he would make it this far into the day ")
print(" jim drives down to the river, there would be too many wittnesses but  " + character_name + " did not care. ")
print(" he got out of his car and survayed his surroundings " + character_name + " realized that there was a couple walking down the path. they wouldnt find him in time, if he hurried. ")
print(" jim touched the warm afternoon water as it flowed by his feet " + character_name + " tied the chain to a rock heavey enough to crush sevral people. ")
print(" the rock was near a spot deep enough to go several feet down " + character_name + " knew this was the perfect spot ")
print(" as jim rolled the rock slowly to the water " + character_name + " knew he was living in his final moments, breathing his last breath. ")
print(" the rock rolled in the water sooner then expected " + character_name + " was sucked under the flowing water ")
print(" jim closed his eyes, the pictures of his friends, family, flashing in his mind " + character_name + " knew this was the end,yet even after al this, jim was still alone. ")
print(" his eyes shut, Jims last look at the world was disorted and corrupt " + character_name + " knew this is what the earth was when the plastic cover melts off the worlds, perfect reality ")
print(" at 1:12 his world went dark " + character_name + " saw nothing ")
print(" just darkness. nothing but darkness. ")